name: Docs for Release

on:
  push:
    tags:
      - '*'

env:
  CI: true

jobs:
  deploy-prod:
    name: Production Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: volta-cli/action@v1

      - name: Install
        run: yarn install
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          ADDON_DOCS_UPDATE_LATEST: 'true'
        run: yarn ember deploy production --verbose --activate
